ALTER SESSION SET "_ORACLE_SCRIPT"=true;

DROP USER BDD2;

CREATE USER BDD2
 IDENTIFIED BY passw0rd
 DEFAULT TABLESPACE USERS
 QUOTA UNLIMITED ON USERS
 ACCOUNT UNLOCK;

GRANT CREATE SESSION, CREATE TABLE TO BDD2; 
GRANT CONNECT, RESOURCE TO BDD2;

GRANT CREATE SESSION, CREATE TABLE, CREATE TRIGGER, CREATE PROCEDURE, CREATE VIEW TO BDD2;
GRANT UNLIMITED TABLESPACE TO BDD2;
